name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
      - run: cd build && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . yablonev@ton.beauty:/var/www/test-task.ton.beauty/build/
      # Configure SSH
      - name: Configure SSH
        run: |
          cat >>~/.ssh/config<<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile "$HOME/.ssh/key"
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: "yablonev"
          SSH_HOST: "ton.beauty"

      - name: Check out the source
        run: ssh production 'rm -rf /var/www/test-task.ton.beauty/html/* && mv /var/www/test-task.ton.beauty/build/* /var/www/test-task.ton.beauty/html/'